branch-defaults:
  main:
    environment: main-my-application
global:
  application_name: abhi_react_app
  default_ec2_keyname: main-my-application
  default_platform: 64bit Amazon Linux 2017.09 v2.6.2 running Ruby 2.4 (Passenger Standalone)
  default_region: ap-south-1
  sc: git