branch-defaults:
  main:
    environment: Myreactapp-env
global:
  application_name: my_react_app
  default_ec2_keyname: Myreactapp-env
  default_platform: 64bit Amazon Linux 2017.09 v3.5.1 running Ruby 2.4 (Passenger Standalone)
  default_region: ap-south-1
  sc: git