version: 2.1

# orbs:
#   node: circleci/aws-elastic-beanstalk@1.0.0

orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@4.7

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      # - node/install
      - run: npm install
      - run:
          name: Run tests
          command: npm test
  deploy:
    working_directory: ~/app
    docker:
      # - image: cimg/deploy:2022.10.1-node
        - image: cimg/base:2023.01
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      # - run: npm install

      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - run:
      #     name: Installing deployment dependencies
      #     working_directory: /
      #     command: |
      #       sudo apt-get -y -qq update
      #       sudo apt-get install python3-pip python3-dev build-essential
      #       sudo pip3 install awsebcli botocore==1.19.63 --upgrade

      # - run:
      #     name: Install Docker client
      #     command: | 
      #         sudo apt-get update
      #         sudo apt install docker.io
      #         # sudo snap install docker

      - run:
        # installs a docker client that will be used to run the docker commands
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            # mv /tmp/docker/* /usr/bin

      - run:
          name: Build application Docker image
          command:  docker build -t stephengrider/docker-react .

      - run: 
          name: Run Docker 
          command: docker run -e CI=true stephengrider/docker-react

      - run:
            working_directory: /
            name: installing ebcli
            command: |
              sudo apt-get -y -qq update
              sudo apt-get install python3-pip python3-dev build-essential
              sudo pip3 install awsebcli botocore==1.19.63 --upgrade
      - run: eb --version
      # - run: 
      #       name: Build application Docker image
      #       command:  docker build -t abhijeet/docker-react .

      - run:
          name: Deploying
          command: eb deploy Myreactapp-env
workflows:
  build_deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main