version: 2.1

# orbs:
#   node: circleci/aws-elastic-beanstalk@1.0.0

orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@4.7

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      # - node/install
      - run: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2.1
  build_deploy:
    jobs:
      - build-and-test
      - aws-elastic-beanstalk/deploy:
            application-name: my_react_app 
            environment-name: Myreactapp-env-1 
            label: Deploy