version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install
      - run: npm install
      - run:
          name: Run tests
          command: npm test
  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

         # Install npm dependencies 🙂
      - run: npm install

        # Make things faster
      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # !!! This installs AWS Elastic Beanstalk CLI 'awsebcli' !!!
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli botocore==1.19.63 --upgrade
      - run:
          name: Deploying
          command: eb deploy $CIRCLE_BRANCH-my-application
workflows:
  build_deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main