version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
       - node/install:
          install-yarn: true
          node-version: '16.13'
      - run:
          name: Run tests
          command: npm test

workflows:
  build_deploy:
    jobs:
      - build-and-test
