version: 2.1

orbs:
  node: circleci/aws-elastic-beanstalk@1.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      # - node/install
      - run: npm install
      - run:
          name: Run tests
          command: npm test
  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      # - run: npm install

      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - run:
      #     name: Installing deployment dependencies
      #     working_directory: /
      #     command: |
      #       sudo apt-get -y -qq update
      #       sudo apt-get install python3-pip python3-dev build-essential
      #       sudo pip3 install awsebcli botocore==1.19.63 --upgrade

      - run:
            working_directory: /
            name: installing ebcli
            command: |
              sudo apt-get -y -qq update
              sudo apt-get install python3-pip python3-dev build-essential
              sudo pip3 install awsebcli botocore==1.19.63 --upgrade
      - run: eb --version
      # - run: 
      #       name: Build application Docker image
      #       command:  docker build -t abhijeet/docker-react .

      - run:
          name: Deploying
          command: eb deploy Myreactapp-env
workflows:
  build_deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main